# =============================================================================
# plot_from_paper.R — Reproduce published GSEA figures from saved intermediates
#
# The original gseKEGG runs did not save the random seed. This script reads the
# original GSEA intermediates (data/) and reproduces the published figures
# exactly, bypassing the non-reproducible GSEA step.
#
# GAM fitting (mgcv::gam, REML) is deterministic; panels fig3c, ef4a, ef4d,
# ef4e are unaffected and generated by Step03_GAM.R.
# =============================================================================

script_dir <- dirname(normalizePath(sub("^--file=", "", commandArgs(trailingOnly = FALSE)[grep("^--file=", commandArgs(trailingOnly = FALSE))])))
setwd(script_dir)

suppressPackageStartupMessages({
  library(tidyverse)
  library(pheatmap)
})

DATA_DIR <- "data"

cat("Plotting from original GSEA intermediates...\n")


# =============================================================================
# plot_refined_heatmap — temporal GSEA refined heatmap with significance
# =============================================================================
plot_refined_heatmap <- function(comp_name, target_keywords, output_file) {
  nes_file    <- file.path(DATA_DIR, paste0("GSEA_Filtered_NES_", comp_name, ".csv"))
  detail_file <- file.path(DATA_DIR, paste0("GSEA_Detailed_", comp_name, ".csv"))
  if (!file.exists(nes_file) || !file.exists(detail_file)) {
    cat(sprintf("  [WARN] Missing GSEA data for %s\n", comp_name)); return()
  }
  full_nes   <- read.csv(nes_file, row.names = 1, check.names = FALSE)
  detail_df  <- read_csv(detail_file, show_col_types = FALSE)

  keep_rows <- unique(unlist(lapply(target_keywords, function(kw) {
    grep(kw, rownames(full_nes), ignore.case = TRUE)
  })))
  if (length(keep_rows) == 0) {
    cat(sprintf("  No target pathways for %s\n", comp_name)); return()
  }
  refined_nes <- full_nes[keep_rows, , drop = FALSE]

  # Build p-value wide matrix matching NES matrix dimensions
  pval_wide <- detail_df %>%
    dplyr::select(Description, TimePoint, pvalue) %>%
    mutate(TimePoint = as.character(TimePoint)) %>%
    pivot_wider(names_from = TimePoint, values_from = pvalue) %>%
    column_to_rownames("Description")
  colnames(pval_wide) <- as.character(colnames(pval_wide))

  refined_pval <- matrix(1, nrow = nrow(refined_nes), ncol = ncol(refined_nes),
                         dimnames = dimnames(refined_nes))
  cr <- intersect(rownames(pval_wide), rownames(refined_pval))
  cc <- intersect(colnames(pval_wide), colnames(refined_pval))
  refined_pval[cr, cc] <- as.matrix(pval_wide[cr, cc])
  refined_pval[is.na(refined_pval)] <- 1

  sig_mat <- matrix("", nrow = nrow(refined_pval), ncol = ncol(refined_pval),
                    dimnames = dimnames(refined_pval))
  sig_mat[refined_pval < 0.05] <- "*"
  sig_mat[refined_pval < 0.01] <- "**"

  pheatmap(refined_nes, scale = "none", cluster_rows = TRUE, cluster_cols = FALSE,
           color = colorRampPalette(c("navy","white","firebrick3"))(100),
           border_color = "grey90", display_numbers = sig_mat, number_color = "black",
           fontsize_number = 12, fontsize_row = 11, fontsize_col = 10,
           main = comp_name, filename = output_file,
           width = 8, height = 3 + nrow(refined_nes) * 0.42)
}


# =============================================================================
# plot_static_kegg — static KEGG dotplot
# =============================================================================
plot_static_kegg <- function(source_csv, output_file, result_name,
                             top_n = 15, plot_width = 7, wrap_width = 15) {
  if (!file.exists(source_csv)) {
    cat(sprintf("  [WARN] %s not found\n", source_csv)); return()
  }
  gsea_df <- read_csv(source_csv, show_col_types = FALSE)
  plot_data <- gsea_df %>%
    mutate(Regulation = if_else(NES > 0, "Activated", "Suppressed")) %>%
    group_by(Regulation) %>%
    slice_min(p.adjust, n = top_n, with_ties = FALSE) %>%
    ungroup() %>%
    mutate(Description = str_wrap(Description, width = wrap_width)) %>%
    arrange(Regulation, NES) %>%
    mutate(Description = fct_inorder(Description))

  p <- ggplot(plot_data, aes(x = NES, y = Description)) +
    geom_point(aes(size = setSize, color = p.adjust)) +
    facet_grid(Regulation ~ ., scales = "free_y", space = "free_y") +
    scale_size_continuous(name = "Gene Count", range = c(3, 8)) +
    scale_color_gradient(low = "red", high = "blue", name = "p.adjust") +
    labs(title = paste("GSEA -", result_name, "KEGG"),
         x = "Normalized Enrichment Score (NES)", y = NULL) +
    theme_bw(base_size = 14) +
    theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
          axis.text.y = element_text(size = 12, lineheight = 0.9),
          strip.text.y = element_text(face = "bold", size = 14),
          panel.spacing = unit(1, "lines"), legend.position = "right")

  ggsave(output_file, p, device = cairo_pdf,
         width = plot_width,
         height = max(6, 2 + 0.5 * nrow(plot_data)),
         limitsize = FALSE)
}


# =============================================================================
# Generate figures
# =============================================================================
# ---- Fig.3D/E: Refined temporal GSEA heatmaps ----

plot_refined_heatmap("Acetic acid vs Control",
  c("Oxidative phosphorylation","SNARE interactions","Propanoate","Glyoxylate",
    "Autophagy","Cell cycle - yeast","Ribosome biogenesis in eukaryotes","Tyrosine"),
  "Original_paper_fig3d.pdf")

plot_refined_heatmap("Hhdrogen peroxide vs Control",
  c("DNA replication","Base excision repair","Mitophagy","Citrate cycle",
    "SNARE","Ribosome biogenesis"),
  "Original_paper_fig3e.pdf")

# ---- EFig.4B/C: Static KEGG dotplots ----

plot_static_kegg(file.path(DATA_DIR, "Acetic_vs_Control_KEGG_data.csv"),
                 "Original_paper_ef4b.pdf", "Acetic_vs_Control")
plot_static_kegg(file.path(DATA_DIR, "H2O2_vs_Control_KEGG_data.csv"),
                 "Original_paper_ef4c.pdf", "H2O2_vs_Control")

# ---- EFig.4F/G: Full temporal GSEA heatmaps ----
for (nm in c("Acetic acid vs Control", "Hhdrogen peroxide vs Control")) {
  src <- file.path(DATA_DIR, paste0("Heatmap_", nm, ".pdf"))
  dst <- if (grepl("Acetic", nm)) "Original_paper_ef4f.pdf" else "Original_paper_ef4g.pdf"
  if (file.exists(src)) file.copy(src, dst, overwrite = TRUE)
}

cat("Done.\n")
